const feature = [
  {
    name: 'Cabang/Outlet',
    free: 'Tersedia(1)',
    starter: 'Tersedia(1)',
    advance: 'Tersedia (~)',
  },
  {
    name: 'Warehouse/Gudang',
    free: 'Tersedia(1)',
    starter: 'Tersedia(1)',
    advance: 'Tersedia (~)',
  },
  {
    name: 'Kategori Produk',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Produk',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Manajemen Aset Tetap',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Data Master Bahan Baku',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Data Pelanggan',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Data Vendor',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Data Salesman',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Data Akun (CoA)',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Data Pajak',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Pesanan Penjualan',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Pengiriman Barang',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Uang Muka Penjualan',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Faktur Penjualan',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Retur Penjualan',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Pembayaran Piutang',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Daftar Piutang (AR Write-Off)',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Penerimaan Barang',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Faktur Pembelian',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Pembayaran Utang Usaha',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Retur Pembelian',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Pengeluaran Kas (Biaya)',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Pemasukan Kas (Penerimaan Lainnya)',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Transfer Kas (Mutasi Internal)',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Stock Opname',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Transfer Gudang',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Pemakaian Persediaan',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Produksi',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Jurnal Umum',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Buku Besar',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Laba Rugi',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Neraca',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Laporan Penjualan',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'laporan Pembelian',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Laporan Kas/Bank',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Kartu Piutang',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Laporan Analisis Umur Piutang',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Laporan Mutasi Barang',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Kartu Stok',
    free: false,
    starter: false,
    advance: true,
  },
  {
    name: 'Laporan Point of Sales (POS)',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Integrasi POS (DivocPOS)',
    free: true,
    starter: true,
    advance: true,
  },
  {
    name: 'Manajemen Meja',
    free: false,
    starter: true,
    advance: true,
  },
  {
    name: 'Kirim Dapur',
    free: false,
    starter: false,
    advance: true,
  },
];

export default feature;
